services:
  balanceme-db:
    image: mongo:latest
    container_name: balanceme-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=balanceme
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - ./balanceme-db-data:/data/db